import { generateAnimationCSS } from './animationEngine'; // ✅ Імпортуємо наш єдиний конвеєр

export const generateFullCSS = (params) => {
  const { animations, color, size, elementType } = params;

  // 1. Пропускаємо всі 3 стани через наш Pipeline
  // Передаємо унікальні ID ('load', 'hover', 'click'), щоб keyframes не конфліктували
  const loadData = generateAnimationCSS(
    animations.load.presetId,
    animations.load,
    'load',
    'load'
  );
  const hoverData = generateAnimationCSS(
    animations.hover.presetId,
    animations.hover,
    'hover',
    'hover'
  );
  const clickData = generateAnimationCSS(
    animations.click.presetId,
    animations.click,
    'click',
    'click'
  );

  // 2. Збираємо всі згенеровані Keyframes
  let keyframesCSS = '';
  if (loadData.keyframes) keyframesCSS += loadData.keyframes + '\n\n';
  // Для hover keyframes зараз буде порожнім (бо ми перевели його на transitions), але залишаємо для сумісності з кастомними пресетами
  if (hoverData.keyframes) keyframesCSS += hoverData.keyframes + '\n\n';
  if (clickData.keyframes) keyframesCSS += clickData.keyframes + '\n\n';

  // 3. Базові стилі
  const baseStyles = `
/* Базові стилі */
.animadiv-element {
  width: ${size}px;
  height: ${size}px;
  background-color: ${color};
  border-radius: ${elementType === 'span' ? '50%' : elementType === 'button' ? '8px' : '16px'};
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1), box-shadow 0.2s;
  cursor: pointer;
  border: none;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}
  `.trim();

  // 4. Правила для станів
  const loadRule =
    loadData.animationStr !== 'none'
      ? `animation: ${loadData.animationStr};`
      : '';
  const clickRule =
    clickData.animationStr !== 'none'
      ? `animation: ${clickData.animationStr};`
      : '';

  // ✅ ТУТ ПРАЦЮЄ НОВА СИСТЕМА HOVER
  let hoverRule = '';
  if (hoverData.transitionCSS) {
    // Якщо Pipeline повернув transition (для scale, slide, fade)
    hoverRule = hoverData.transitionCSS;
  } else if (hoverData.animationStr !== 'none') {
    // Fallback: якщо це складний ефект, який ще працює на keyframes
    hoverRule = `animation: ${hoverData.animationStr};`;
  }

  const stateRules = `
/* Анімація появи */
.animadiv-element.is-load {
  ${loadRule}
}

/* Анімація при наведенні */
.animadiv-element:hover {
  ${hoverRule}
  ${animations.hover.presetId === 'none' ? 'transform: scale(1.05);' : ''}
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
}

/* Анімація при кліку */
.animadiv-element:active {
  ${clickRule}
  ${animations.click.presetId === 'none' ? 'transform: scale(0.95);' : ''}
}
  `.trim();

  return `/* Generated by AnimaDiv */\n\n${keyframesCSS.trim()}\n\n${baseStyles}\n\n${stateRules}`;
};
