import { animationPresets } from '../data/presets';

// Таска 2: Унікальне ім'я
export const makeKeyframesName = (presetId) => `ag_${presetId}`;

// Таска 3 та 4: Генерація вмісту
export const generateKeyframesCSS = (params) => {
  const { presetId } = params;
  const preset = animationPresets.find((p) => p.id === presetId);
  if (!preset || typeof preset.keyframes !== 'function') return '';
  return `@keyframes ${makeKeyframesName(presetId)} {\n${preset.keyframes(params)}\n}`;
};

export const generateAnimationClassCSS = (params) => {
  return `.ag-animated {
  animation-name: ${makeKeyframesName(params.presetId)};
  animation-duration: ${params.duration}ms;
  animation-timing-function: ${params.easing};
  animation-fill-mode: both;
}`;
};

// Таска 5: Фінальна збірка
export const generateFullCSS = (params) => {
  return `/* Generated by AnimaDiv */\n${generateKeyframesCSS(params)}\n\n${generateAnimationClassCSS(params)}`;
};
