import { animationPresets } from '../data/presets';

// 1. Уніфікація імен keyframes (ag_ - наш префікс)
const makeKeyframesName = (presetId) => `ag_${presetId}`;

// 2. Функція для створення одного правила анімації
const getAnimationRule = (stateConfig) => {
  if (!stateConfig || stateConfig.presetId === 'none') return '';

  return `animation: ${makeKeyframesName(stateConfig.presetId)} ${stateConfig.duration}ms ${stateConfig.easing} both;`;
};

export const generateFullCSS = (params) => {
  const { animations, color, size, elementType } = params;

  // --- ГЕНЕРАЦІЯ KEYFRAMES ---
  // Використовуємо Set, щоб не дублювати однакові анімації в CSS
  const usedPresets = new Set();
  Object.values(animations).forEach((anim) => {
    if (anim.presetId !== 'none') usedPresets.add(anim.presetId);
  });

  let keyframesCSS = '';
  usedPresets.forEach((id) => {
    const preset = animationPresets.find((p) => p.id === id);
    if (preset && typeof preset.keyframes === 'function') {
      // Знаходимо параметри стану, який використовує цей пресет (для інтенсивності)
      const stateName = Object.keys(animations).find(
        (key) => animations[key].presetId === id
      );
      keyframesCSS += `@keyframes ${makeKeyframesName(id)} {\n${preset.keyframes(animations[stateName])}\n}\n\n`;
    }
  });

  // --- ГЕНЕРАЦІЯ СТИЛІВ ЕЛЕМЕНТА ---
  const baseStyles = `
/* Базові стилі */
.animadiv-element {
  width: ${size}px;
  height: ${size}px;
  background-color: ${color};
  border-radius: ${elementType === 'span' ? '50%' : elementType === 'button' ? '8px' : '16px'};
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1), box-shadow 0.2s;
  cursor: pointer;
  border: none;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}
  `.trim();

  // --- ГЕНЕРАЦІЯ ПРАВИЛ ДЛЯ СТАНІВ ---
  const stateRules = `
/* Анімація появи */
.animadiv-element.is-load {
  ${getAnimationRule(animations.load)}
}

/* Анімація при наведенні */
.animadiv-element:hover {
  ${getAnimationRule(animations.hover)}
  ${animations.hover.presetId === 'none' ? 'transform: scale(1.05);' : ''}
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
}

/* Анімація при кліку */
.animadiv-element:active {
  ${getAnimationRule(animations.click)}
  ${animations.click.presetId === 'none' ? 'transform: scale(0.95);' : ''}
}
  `.trim();

  return `/* Generated by AnimaDiv */\n\n${keyframesCSS}\n${baseStyles}\n\n${stateRules}`;
};
